// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hora_Komdelli;

namespace hora_Komdelli.Migrations
{
    [DbContext(typeof(Conexao))]
    partial class ConexaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("hora_Komdelli.Corte_executado", b =>
                {
                    b.ToTable("corte_executado");
                });

            modelBuilder.Entity("hora_Komdelli.Corte_planejado", b =>
                {
                    b.ToTable("corte_planejado");
                });

            modelBuilder.Entity("hora_Komdelli.Op_executado", b =>
                {
                    b.ToTable("op_executado");
                });

            modelBuilder.Entity("hora_Komdelli.Op_planejado", b =>
                {
                    b.ToTable("op_planejado");
                });
#pragma warning restore 612, 618
        }
    }
}
